# Colors
background #1e1e1e
foreground #c5c8c6

# Font
font_family monospace
font_size 16

# Padding
# window_padding_width 40
window_padding_width 5

# Opacity
background_opacity 0.8

# Live reload
# kitty reloads config automatically by default,
# but you can manually reload with:
# Ctrl+Shift+F5
#

confirm_os_window_close 0
enable_audio_bell no
