# ~/.config/mpv/input.conf

# Basic playback
SPACE cycle pause
LEFT seek -5
RIGHT seek 5
UP add speed 0.1
DOWN add speed -0.1
r set speed 1.0

# Volume
9 add volume -5
0 add volume 5

# Fullscreen
f cycle fullscreen

# Subtitles
v cycle sub
b cycle sub-visibility
j cycle sub

# Screenshot
s screenshot

# Loop toggle
l cycle loop-file

# Shader toggles
F1 change-list glsl-shaders toggle "~/.config/mpv/shaders/eye_comfort.glsl"
F2 change-list glsl-shaders toggle "~/.config/mpv/shaders/grayscale.glsl"

